version: '3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  dbdata: